### ISSUE TITLE
Docker搭建Npm私服Verdaccio

### ISSUE THREAD

**Issue by jkhrdhr** [jkhrdhr/my-voice#1]
## 背景

来公司第一个任务就是封装低代码平台的部分功能，并且部署到npm私服上去，研究了一番有所成就。利用`Docker`部署`Verdaccio`实现。

## 安装verdaccio镜像
首先我们服务器上要装有`docker`。
* 查询可安装的Verdaccio，可以看到verdaccio/verdaccio，表示最新版本。
```sh
docker search verdaccio
```
* 安装
```sh
docker pull verdaccio/verdaccio
```

此时我们将verdaccio镜像拉取完毕，我们可以使用命令查看镜像
* 查看安装的所有镜像
```
docker images
```
## 创建并启动verdaccio容器
接下来开始做一些创建容器前的准备工作啦

在root目录下创建verdaccio/conf目录，conf目录下放置config.yaml和htpasswd文件。config.yaml是verdaccio的配置文件，htpasswd是放置npm账户的用户名和密码，但是用户名和密码需要进行MD5编码。其中-p是指递归循环创建目录。[在线编码网址](https://tool.oschina.net/htpasswd?spm=a2c6h.12873639.article-detail.10.51927d84mceTve)
```
mkdir -p /root/verdaccio/conf  
```
* 放置包文件
```
mkdir -p /root/verdaccio/storage
```
* 给容器对物理目录的读写权限
```
chown -R 100:101 /root/verdaccio/
```
* 创建config.yaml配置文件并进行设置
```
cd /root/verdaccio/conf
vi config.yaml
```
```
# 所有包的保存路径  
 storage: /verdaccio/storage/data  
# 插件的保存路径  
 plugins: /verdaccio/plugins  
 
 # 通过web访问  
 web:    
   title: "Verdaccio"  
   
 # 账号密码文件，初始不存在  
 auth:    
     htpasswd:      
     file: /verdaccio/storage/htpasswd  
     algorithm: md5 # 这里选择 md5 作为加密算法
     # max_users: -1 # 不允许自由注册    
     # max_users：1000      
     # 默认1000，允许用户注册数量。为-1时，不能通过 npm adduser 注册，此时可以直接修改 file 文件添加用户。  
     # 本地不存在时，读取仓库的地址  
uplinks:    
    npmjs:      
      url: https://registry.npmjs.org/ 
    yarn:
       url:https://registry.yarnpkg.com/  
      
# 对包的访问操作权限，可以匹配某个具体项目，也可以通配  
# access 访问下载；publish 发布；unpublish 取消发布；  
# proxy 对应着uplinks名称，本地不存在，去unplinks里取  
# $all 表示所有人都可以执行该操作  
# $authenticated 已注册账户可操作  
# $anonymous 匿名用户可操作  
# 还可以明确指定 htpasswd 用户表中的用户，可以配置一个或多个。 
packages:    
  '@*/*':      
    access: $all      
    publish: $authenticated      
    unpublish: $authenticated      
    proxy: npmjs        
  '**':      
    access: $all      
    publish: $authenticated      
    unpublish: $authenticated      
    proxy: npmjs  
    
# 服务器相关  
sever:    
  keepAliveTimeout: 60  
  
middlewares:    
  audit:      
    enabled: true  
    
# 日志设定  
logs: { type: stdout, format: pretty, level: http }
```

* 生成htpasswd文件，放置加密后的账户密码
```
touch htpasswd
```
* htpasswd 文件具体内容如下：
```
guilai:$apr1$ajqWS1jR$02HsYf6WZWPZkV9/slcM1
```
* 接下来我们就开始创建并启动verdaccio容器啦
```
docker run -it --name verdaccio -p 4873:4873 -v /root/verdaccio/conf:/root/verdaccio/conf -v /root/verdaccio/storage:/root/verdaccio/storage   verdaccio/verdaccio
```
-p：端口映射（宿主机端口：容器端口，即将主机端口映射到容器端口）<br/>
-v：容器目录映射到本地目录（宿主机文件目录：容器文件目录，将宿主机文件挂载到容器目录）<br/>
-d：后台启动容器<br/>
-it：以交互式模式启动容易<br/>
–name：容器名称

## nrm 的使用
* 安装
```
yarn add nrm global
```
* 添加本地镜像
```
nrm add ceshiRegistry http:xxxxx:4873
```
* 查看所有的源
```
nrm ls
```
* 使用源
```
nrm use ceshiRegistry
```
* 删除源(博士只是展示该命令，实际不用删除)
```
nrm del ceshiRegistry
```
## 将组件库发布到私有服务
* 添加用户
```
npm adduser //设置了源为私有服务的源
npm adduser --registry http://xxxxxx:4873 //未设置源
```
* 发布
```
npm publish //设置了源为私有服务的源
npm publish --registry http://xxxxxx:4873 //未设置源
```
发布后可以查看自己上传的组件库

![](./69a33ce095dc4df2bee7f93d9d5517f0.png)

### 方法1：设置安装源为私有服务的源
```
nrm use ceshiRegistry
```
### 方法2：新建.npmrc文件
```
always-auth=true
registry=http://xxxxx:4873/
```
### 然后

`npm install  //安装的就是你设置的源`
